#include "stdafx.h"
#include "Vertex.h"
#define VERTEX_DATA D3D11_INPUT_PER_VERTEX_DATA
#define DXGI_FORMAT DXGI_FORMAT_R32G32B32_FLOAT

D3D11_INPUT_ELEMENT_DESC Vertex::Desc[]= //책 찾아보기
{
	{"POSITION",0,DXGI_FORMAT,0,0,VERTEX_DATA,0}//SemanticName:구분하는 이름 ,SemanticIndex:시멘틱번호
	//DXGI_FORMAT_R32G32B32_FLOAT RGB32비트 XYZ는 4바이트에 플롯형태이다
	//AlignedButeOffset :정렬된 바이트옵셋 어디까지가 포지션데이터인지 알려준다.
};

D3D11_INPUT_ELEMENT_DESC VertexColor::Desc[] = 
{
	{ "POSITION",0,DXGI_FORMAT,0,0,VERTEX_DATA,0 },
    { "COLOR",0,DXGI_FORMAT_R32G32B32A32_FLOAT,0,D3D11_APPEND_ALIGNED_ELEMENT,VERTEX_DATA,0 }
};

D3D11_INPUT_ELEMENT_DESC VertexTexture::Desc[] =
{
	{ "POSITION",0,DXGI_FORMAT,0,0,VERTEX_DATA,0 },
    { "TEXCOORD",0,DXGI_FORMAT_R32G32_FLOAT,0,D3D11_APPEND_ALIGNED_ELEMENT,VERTEX_DATA,0 }
};
